### ISSUE TITLE
Disk Quota exceeded after only 4 languages 

### ISSUE THREAD

**Issue by joeybodoia** [mikeizbicki/chajda#10]
Hey Mike,

I'm working on writing the benchmark test for augments_fasttext parametrized on all languages that spacy offers. However, the disk quota is exceeded after only 4 languages (english not included). 

This doesn't seem unreasonable to me because for every fasttext model, there is also an annoy index that takes up significant space. However, it's not clear to me how to get around this issue, especially for the test case that involves all 157 languages that fasttext offers. 

One idea that came to mind for me (not sure if this is doable) is to test 3 languages at a time. That is, structure the benchmark tests so they load three languages, test 3 languages, remove the downloads, and repeat. This approach doesn't seem ideal though.

Do you have any ideas for how to get passed this roadblock?

**Comment by mikeizbicki** [comment]
You have 100gb of disk space allocated, so only being able to use 3 languages at a time seems pretty bad to me.  My estimation is that each language should take max 2-3GB.  I think the fast text and annoy files should be about the same size, maybe a 2x overhead for annoy but not much more than that.  My guess is that you're keeping around some extra files that you don't actually need somewhere.

Also, you can get more efficient by discarding the fasttext files after you've used them to build the annoy index.  The annoy index should contain all of the same information, so you won't need to use the fasttext files anymore.  That might require restructuring your code somewhat, so it may or may not be worth the effort.
